version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=asaph
      - POSTGRES_PASSWORD=1a2b3c
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050